apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'
    isDefault: true
    editable: true
  - name: 'nginx'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://nginx-exporter:9113'
    isDefault: false
    editable: true
  - name: 'postgres'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://postgres-exporter:9187'
    isDefault: false
    editable: true
  - name: 'django'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://django:8000'
    isDefault: false
    editable: true
  - name: 'node'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://node-exporter:9100'
    isDefault: false
    editable: true
